### ISSUE TITLE
failure to build/run on debian bookworm

### ISSUE THREAD

**Issue by kmptkp** [wayland-transpositor/wprs#35]
wprsd wasn't able to run after building on a fresh installation of debian bookworm. But first, a few steps that might be good to add to the build instructions:

1. I needed to `sudo apt-get install pkg-config libwayland-dev libxkbcommon-dev` before I could build (not sure about libwayland-dev)

2. after building, something like this is required in order for the instructions to work:

```
sudo cp target/release-lto/wprsd /usr/bin/
sudo cp wprsd.service /etc/systemd/user/
```

3. Once all is in place, trying to run results in `panicked at src/bin/wprsd.rs:228:10` which turns out to be related to: `config file does not exist at ...`. Maybe the instructions could be rephrased to note that generating the config is not optional. Ie:

```
mkdir ~/.config/wprs
wprsd --print-default-config-and-exit=true > ~/.config/wprs/wprsd.ron
```

4. rerunning:

```
2024-05-11T19:30:29.432673Z ERROR ThreadId(01) wprs::utils: src/utils.rs:80: panic!:
panicked at src/bin/wprsd.rs:228:10:
error starting xwayland-xdg-shell: Os { code: 2, kind: NotFound, message: "No such file or directory" }
disabled backtrace
thread 'main' panicked at src/bin/wprsd.rs:228:10:
error starting xwayland-xdg-shell: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I probably missed something, but I'm not sure what :)

**Comment by nicolasavru** [comment]
More generally, wprsd expects xwayland-xdg-shell to be in PATH. That's what that error is about.

The config file is indeed optional. src/bin/wprsd.rs:228 is the launching xwayland-xdg-shell error.

I'm working on some packaging scripts and improving the directions, sorry that's not in place yet.

**Comment by kmptkp** [comment]
Thank you, both of these solutions worked.

**Comment by kmptkp** [comment]
Thank you, both of these solutions worked.
